apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  labels:
    app: dubbogo-server
  name: dubbogo-triple-server-2c-2g
  namespace: dubbogo-adaptivesvc
spec:
  containers:
    - env:
        - name: MIN_OFFLINE_DURATION
          value: 5s
        - name: MIN_ONLINE_DURATION
          value: 20s
        - name: OFFLINE_RATIO
          value: "0"
        - name: TIMEOUT_DURATION
          value: 10s
        - name: TIMEOUT_RATIO
          value: "0"
      image: zhangyepeng/dubbogo-triple-server-adasvc
      imagePullPolicy: Always
      name: dubbogo-server
      ports:
        - containerPort: 20001
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: "2"
          memory: 2Gi
      volumeMounts:
        - mountPath: /dubbogo/conf
          name: dubbogo-conf
  restartPolicy: Always
  volumes:
    - configMap:
        name: dubbogo-triple-server-conf
      name: dubbogo-conf
