apiVersion: batch/v1
kind: Job
metadata:
  name: dubbogo-client
  namespace: dubbogo-adaptivesvc
spec:
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: dubbogo-client
          image: xavierniu/dubbogo-triple-client-adasvc
          imagePullPolicy: Always
          env:
            - name: PARALLEL
              value: "10"
      restartPolicy: Never
  backoffLimit: 4
