apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbogo-triple-server
  namespace: dubbogo-adaptivesvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dubbogo-server
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      labels:
        app: dubbogo-server
    spec:
      containers:
        - name: dubbogo-server
          image: xavierniu/dubbogo-triple-server-adasvc
          env:
          - name: MIN_OFFLINE_DURATION
            value: "5s"
          - name: MIN_ONLINE_DURATION
            value: "20s"
          - name: OFFLINE_RATIO
            value: "0.2"
          - name: TIMEOUT_DURATION
            value: "10s"
          - name: TIMEOUT_RATIO
            value: "0.5"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              cpu: "2"
              memory: 2Gi
          ports:
            - containerPort: 20001
            - containerPort: 9090
          volumeMounts:
            - mountPath: /dubbogo/conf
              name: dubbogo-conf
      volumes:
        - configMap:
            name: dubbogo-triple-server-conf
          name: dubbogo-conf

